### ISSUE TITLE
Not finding any references

### ISSUE THREAD

**Issue by brandon-sling** [launchdarkly/ld-find-code-refs#101] opened 2019-09-24 20:02 UTC
After updating to version 1.3.0 no references are being found. Downgraded to 1.2.0 and everything is working again.

version 1.3.0 is a dryRun but a normal run doesn't find anything either.

Version 1.3.0
```
ld-find-code-refs -accessToken="TOKEN" -projKey="proj" -repoName="core-ui" -dir="./" -repoUrl="internal.com/repo" -dryRun="true" -debug="true" -defaultBranch="develop"
ld-find-code-refs version 1.3.0
DEBUG: 2019/09/24 13:58:27 git.go:67: identified branch name: develop
INFO: 2019/09/24 13:58:27 git.go:41: git branch: develop
DEBUG: 2019/09/24 13:58:27 git.go:82: identified head sha: 29460504d49acd1a99d6db04bb5435659b8e9755
INFO: 2019/09/24 13:58:28 search.go:87: finding code references with delimiters: ["'`]
DEBUG: 2019/09/24 13:58:28 search.go:58: searching for flags in group: [0, 62]
     FLAG     | # REFERENCES  
+-------------+--------------+
  Other flags |            0  
INFO: 2019/09/24 13:58:28 coderefs.go:154: dry run found 0 code references across 63 flags and 0 files
```
Version 1.2.0
```
ld-find-code-refs -accessToken="TOKEN" -projKey="proj" -repoName="core-ui" -dir="./" -repoUrl="internal.com/repo" -contextLines=-1 -debug="true" -defaultBranch="develop"
ld-find-code-refs version 1.2.0
INFO: 2019/09/24 13:50:56 command.go:199: absolute directory path: /Users/brandon/git/jcl/core-ui
DEBUG: 2019/09/24 13:50:56 command.go:82: identified branch name: develop
INFO: 2019/09/24 13:50:56 command.go:56: git branch: develop
DEBUG: 2019/09/24 13:50:56 command.go:97: identified head sha: 29460504d49acd1a99d6db04bb5435659b8e9755
DEBUG: 2019/09/24 13:50:56 client.go:344: [DEBUG] GET https://app.launchdarkly.com/api/v2/code-refs/repositories/core-ui
DEBUG: 2019/09/24 13:50:56 client.go:344: [DEBUG] POST https://app.launchdarkly.com/api/v2/code-refs/repositories
INFO: 2019/09/24 13:50:57 coderefs.go:215: finding code references with delimiters: ["'`]
INFO: 2019/09/24 13:50:57 coderefs.go:135: sending 16 code references across 63 flags and 5 files to LaunchDarkly for project: proj
                FLAG               | # REFERENCES  
+----------------------------------+--------------+
  cmwnext-mytv-screen              |            3  
  bottom-nav                       |            2  
  react-mytv-screen                |            2  
  splashscreen-browse-option       |            1  
  launch-directly-as-prospect      |            1  
  micro-guide                      |            1  
  upcoming-content-reminders       |            1  
  watch-pass                       |            1  
  cmwnext-client-config            |            1  
  my-tv-recommended-for-you-ribbon |            1  
  cmwnext-dynamic-screens          |            1  
  cmwnext-search-screen            |            1  
  Other flags                      |            0  
DEBUG: 2019/09/24 13:50:57 client.go:344: [DEBUG] PUT https://app.launchdarkly.com/api/v2/code-refs/repositories/core-ui/branches/develop
DEBUG: 2019/09/24 13:50:58 command.go:110: found 52 branches on remote
DEBUG: 2019/09/24 13:50:58 client.go:344: [DEBUG] GET https://app.launchdarkly.com/api/v2/code-refs/repositories/core-ui/branches
INFO: 2019/09/24 13:50:58 coderefs.go:186: found 0 stale branches to be marked for deletion```

**Comment by atrakh** [comment] 2019-09-24 20:36
Hi @brandon-sling,

Thank you for reporting this. I've been able to reproduce this issue on my machine. The issue appears to a regression when a relative path is supplied to the `dir` option. Can you confirm 1.3.0 works if you use an absolute path?

We'll have a fix for this issue out shortly.

**Comment by brandon-sling** [comment] 2019-09-24 20:53
Actually 1.3.0 is not working with an absolute path either
`... -dir="/Users/brandon/git/jcl/core-ui/" ...` <- switching to this still finds 0

**Comment by brandon-sling** [comment] 2019-09-24 21:01
as a side note, `ag` finds the references i would expect `ld-find-code-refs` to find. They just seem to get tossed out somewhere.

**Comment by atrakh** [comment] 2019-09-24 21:04
>Actually 1.3.0 is not working with an absolute path either
... -dir="/Users/brandon/git/jcl/core-ui/" ... <- switching to this still finds 0

Thanks for confirming that.

We've just released [1.3.1](https://github.com/launchdarkly/ld-find-code-refs/releases/tag/1.3.1), which should resolve the issue at least for relative paths.

I did some additional testing after reading this message-- 1.3.1 should also fix the problem for dirs with trailing slashes. If you run 1.3.0 with just the last trailing slash removed from your path, I would expect it to find code references. Please let me know if that's not the case.

>as a side note, ag finds the references i would expect ld-find-code-refs to find. They just seem to get tossed out somewhere.

Interesting-- what do your args to `ag` look like? From my investigation, I found that `ld-find-code-refs` was generating invalid arguments when a relative path was provided due to this regression.

**Comment by brandon-sling** [comment] 2019-09-24 21:05
upgrading to 1.3.1 fixes the issue with both the absolute and relative paths i was experiencing. Weirdly absolute paths worked on other repos, just not the "core-ui" one.

**Comment by brandon-sling** [comment] 2019-09-24 21:07
It looks like the trailing "/" character in the path was what was causing the problem. Older runs on 1.3.0 without the trailing "/" were working.

**Comment by atrakh** [comment] 2019-09-24 21:10
Got it! Thanks for confirming that 1.3.1 resolves the issue, and for your patience as we fixed this bug.

Please don't hesitate to reach out again if you have any questions :)

**Closed by atrakh** 2019-09-24 21:10 UTC
